/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dort_islem.h)                                               */
/* BINDTOOL_HEADER_FILE_HASH(515e18884c87d588e083683f06af511e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aobb/dort_islem.h>

template <typename T>
void bind_dort_islem_template(py::module& m, const char* classname)
{
    using dort_islem = gr::aobb::dort_islem<T>;

    py::class_<dort_islem,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<dort_islem>>(m, classname)
        .def(py::init(&gr::aobb::dort_islem<T>::make),
             py::arg("add") = true,
             py::arg("sub") = false,
             py::arg("mul") = false,
             py::arg("div") = false)
        .def("set_dort_islem_type",
             &dort_islem::set_dort_islem_type,
             py::arg("add"),
             py::arg("sub"),
             py::arg("mul"),
             py::arg("div"));
}

void bind_dort_islem(py::module& m)
{
    bind_dort_islem_template<std::int16_t>(m, "dort_islem_ss");
    bind_dort_islem_template<std::int32_t>(m, "dort_islem_ii");
    bind_dort_islem_template<float>(m, "dort_islem_ff");
    bind_dort_islem_template<gr_complex>(m, "dort_islem_cc");
}
