/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vector_to_file.h)                                               */
/* BINDTOOL_HEADER_FILE_HASH(9eb9902197453957a34a06b176f2e3ed)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aobb/vector_to_file.h>


void bind_vector_to_file_template(py::module& m, const char* classname)
{
    using vector_to_file = gr::aobb::vector_to_file;

    py::class_<vector_to_file,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<vector_to_file>>(m, classname)
        .def(py::init(&vector_to_file::make),
             py::arg("itemsize"),
             py::arg("filename"),
             py::arg("append") = false,
             py::arg("threshold") = 0.5,
             py::arg("samples_per_symbol") = 100)


        .def("open", &vector_to_file::open, py::arg("filename"))
        .def("set_unbuffered", &vector_to_file::set_unbuffered, py::arg("unbuffered"))

        .def("close", &vector_to_file::close)


        ;
}

void bind_vector_to_file(py::module& m)
{
    bind_vector_to_file_template(m, "vector_to_file");
}
